### ISSUE TITLE
Can't send commands anymore

### ISSUE THREAD

**Issue by Sinnersslayer** [xenonsmurf/Servus#1]
Hi there!
I love new 1.0.0.8 update but now I can't sent commands from the chat line.
When I set my default channel it sends all commans to that channel like a normal message.
For /say it just say /ma flash <t> instead of sending that command directly to the game like before.
Any way to fix it?

**Comment by xenonsmurf** [comment]
Hey Sinnersslayer, I will take a look. tbh i haven't done anything with servus for a while and just released the source if anyone wanted to play around with it.

**Comment by xenonsmurf** [comment]
Fixed and tested any text command starting with a "/" will now be sent to the game and not the default channel.
